language: python
python:
  - "3.8"

branches:
  only:
    - test

env:
  global:
    - SECRET_KEY="test"
    - DB_NAME="test_db"
    - DB_USER=postgres
    - DB_PASS=""
    - DB_HOST=localhost
    - DB_PORT=""

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database test_db;' -U postgres

script: python manage.py test