name: test ci

on:
  push:
    branches:
      - test


env:
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_HOST: localhost
  DB_PORT: 5432

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull code
        run: cd /home/ubuntu/app && git pull

      - name: run docker-compose
        run: cd /home/ubuntu/app && docker-compose up -d
