name: test ci

on:
  push:
    branches:
      - test


env:
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_HOST: localhost
  DB_PORT: 5432

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          ./manage.py test

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2

      - name: Clone repository
      - run: git clone

      - name: create file named xd
      - run: touch xd
