name: test ci

on:
  push:
    branches:
      - test


env:
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_HOST: localhost
  DB_PORT: 5432

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull code
        run: cd /home/ubuntu/app/pyshoppe && git checkout test && git pull

      - name: stop docker-compose
        run: cd /home/ubuntu/app/pyshoppe && docker compose -f docker-compose.yml down

      - name: run docker-compose
        run: cd /home/ubuntu/app/pyshoppe && docker compose -f docker-compose.yml up --build -d

